import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { computeSourceFingerprint } from "../src/runtime/evidence/source-fingerprint.js";
import {
  readRegisteredArtifactDigests,
  registerGeneratedArtifactIntegrity,
  verifyArtifactIntegrity,
} from "../src/runtime/evidence/artifact-integrity.js";

describe("evidence verification fails closed", () => {
  test("missing fingerprint source is explicitly unverifiable instead of an accepted empty map", () => {
    const root = mkdtempSync(join(tmpdir(), "yolo-fingerprint-missing-"));
    try {
      const result = computeSourceFingerprint(root, ["src/missing.ts"]);

      assert.equal(result.status, "unverifiable");
      assert.deepEqual(result.files, {});
      assert.deepEqual(result.unverifiable_paths, ["src/missing.ts"]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("existing non-source artifact without expected digest is not silently passed", () => {
    const root = mkdtempSync(join(tmpdir(), "yolo-artifact-unverified-"));
    try {
      const artifact = join(root, "report.json");
      writeFileSync(artifact, "{}\n", "utf8");

      const result = verifyArtifactIntegrity([artifact], { rootDir: root });

      assert.equal(result.status, "fail");
      assert.equal(result.unverified.length, 1);
      assert.equal(result.unverified[0].path, "report.json");
      assert.equal(result.unverified[0].issue, "expected_digest_missing");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("artifact generated by the current execution registers its digest during creation", () => {
    const root = mkdtempSync(join(tmpdir(), "yolo-artifact-generated-"));
    try {
      const artifact = join(root, "report.json");
      writeFileSync(artifact, "{}\n", "utf8");

      const result = registerGeneratedArtifactIntegrity([artifact], { rootDir: root });

      assert.equal(result.status, "pass");
      assert.equal(result.artifacts[0].digest_match, true);
      assert.equal(result.artifacts[0].expected_sha256, result.artifacts[0].sha256);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("generated artifact digest registration persists across lifecycle invocations", () => {
    const root = mkdtempSync(join(tmpdir(), "yolo-artifact-persisted-"));
    const stateRoot = join(root, ".yolo");
    try {
      const artifact = join(root, "prd.json");
      mkdirSync(join(stateRoot, "keys"), { recursive: true });
      writeFileSync(join(stateRoot, "keys", "ledger.hmac"), "artifact-registry-test-key", "utf8");
      writeFileSync(artifact, "{}\n", "utf8");

      registerGeneratedArtifactIntegrity([artifact], {
        rootDir: root,
        stateRoot,
        source: "test-prd-writer",
      });
      const registered = readRegisteredArtifactDigests([artifact], { rootDir: root, stateRoot });
      const verified = verifyArtifactIntegrity([artifact], {
        rootDir: root,
        expectedSha256ByPath: registered.expected_sha256_by_path,
      });

      assert.equal(registered.status, "pass");
      assert.equal(registered.registered_count, 1);
      assert.equal(verified.status, "pass");

      writeFileSync(artifact, "{\"tampered\":true}\n", "utf8");
      const tampered = verifyArtifactIntegrity([artifact], {
        rootDir: root,
        expectedSha256ByPath: registered.expected_sha256_by_path,
      });
      assert.equal(tampered.status, "fail");
      assert.equal(tampered.digest_mismatches.length, 1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
